name: ArisNetwork-Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        [cite_start]uses: actions/checkout@v4 [cite: 22]

      - name: Set up JDK 21
        [cite_start]uses: actions/setup-java@v4 [cite: 22]
        with:
          java-version: '21'
          distribution: 'temurin'
          [cite_start]cache: maven [cite: 22]

      - name: Build with Maven
        run: mvn -B package

      # BƯỚC QUAN TRỌNG ĐỂ THẤY CHỖ TẢI
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DonutShop-Finished
          path: target/*.jar
